### ISSUE TITLE
Project Title

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/slideshow#1]
**slideshow** is not a very good name.

Please comment with suggestions for a better name!

**Comment by ArtskydJ** [comment]
**songshow**
**songslides**
**slidesong**

_Edit:_ actually these are not very good names, because this project is not meant _only_ for songs. (E.g. we also want to display the welcome picture, responsive readings, catechism, etc.)

**Comment by ArtskydJ** [comment]
Since this is very DCC specific, maybe it should be called **dcc-slideshow**.

**Comment by TehShrike** [comment]
Yeah.  Maybe once we have it all done and working, we can identify the parts of it that are generalizable and create a new module with a general name at that point.
