### ISSUE TITLE
Figure out how to sync project/song files between computers

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/slideshow#11]
There needs to be a way to easily sync the created slides with the computer that will project the slides.

[Integrate with dropbox](https://github.com/dropbox/dropbox-js/blob/stable/guides/getting_started.md)?

**Comment by ArtskydJ** [comment]
Instead of dropbox integration in the website, the projecting computer could host a static server that serves the slideshow software files, and serves the dropbox folder on that computer. Then you'd go to http://localhost:8080 and all your slideshow would be hosted.

This could be a much more complicated setup. Hopefully there would be a shortcut that you'd double-click and it would start the server and open the webpage.

**Comment by TehShrike** [comment]
I've heard of people doing things with Dropbox's "share this directory via url" functionality - maybe we could host a static server that way?  And launch a local server from that same directory for offline use?

Then the directory could contain the html/js, and use XHRs to pull in the files.

**Comment by ArtskydJ** [comment]
[Here](https://www.dropbox.com/help/167) is the documentation for dropbox's "share via url" feature.

**Comment by ArtskydJ** [comment]
Given a magical dropbox link, and possibly a project file path, it could get the project file, and the song files, via xhr, like it is doing now, and the whole thing could be client-side, and you wouldn't have to sign in to dropbox.

I like that idea.

Is leaking the link an issue? If it is an issue, the link could be saved in localstorage, but if not, the link could be hardcoded.
