### ISSUE TITLE
Use z-index instead of display none

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/slideshow#30]
Instead of `:not(.show) { display: none }` do `.show { z-index: 999; }` and make the slides absolutely positioned on top of each other.

I think this will help make fading possible, as well as fx such as sliding without funny text wrapping at page edges during the slide.

**Comment by TehShrike** [comment]
You could set the z-index of each slide to its position in the slide deck! :-D

**Comment by ArtskydJ** [comment]
https://css-tricks.com/absolute-positioning-inside-relative-positioning/

**Comment by ArtskydJ** [comment]
Fixed by https://github.com/ArtskydJ/dcc-slideshow/commit/fa71d99550480bbe13df51dd1649bc0e3d456dd3.
